# MNIST Classification with DNN

In [0]:
import tensorflow as tf

In [0]:
#Reset tensorflow graph
tf.reset_default_graph()

Step 1 : Collect Data

In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnists = input_data.read_data_sets('MNIST_data')
trai = mnists.train.images
trt = mnists.train.labels
trt[0:1]

Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.
Instructions for updating:
Please write your own downloading logic.
Instructions for updating:
Please use urllib or similar directly.
Successfully downloaded train-images-idx3-ubyte.gz 9912422 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-images-idx3-ubyte.gz
Successfully downloaded train-labels-idx1-ubyte.gz 28881 bytes.
Instructions for updating:
Please use tf.data to implement this functionality.
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Successfully downloaded t10k-images-idx3-ubyte.gz 1648877 bytes.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Successfully downloaded t10k-labels-idx1-ubyte.gz 4542 bytes.
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz
Instructions for updating:
Please use alternatives such as official/mnist/dataset.py from tensorflow/models.


array([7], dtype=uint8)

In [0]:
trai

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.]], dtype=float32)

In [0]:
trai.shape

(55000, 784)

In [0]:
from tensorflow.examples.tutorials.mnist import input_data
mnist = input_data.read_data_sets('MNIST_data', one_hot=True)

Extracting MNIST_data/train-images-idx3-ubyte.gz
Extracting MNIST_data/train-labels-idx1-ubyte.gz
Instructions for updating:
Please use tf.one_hot on tensors.
Extracting MNIST_data/t10k-images-idx3-ubyte.gz
Extracting MNIST_data/t10k-labels-idx1-ubyte.gz


In [0]:
mnist

Datasets(train=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f37ea430320>, validation=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f37ea430080>, test=<tensorflow.contrib.learn.python.learn.datasets.mnist.DataSet object at 0x7f37ea430470>)

Step 1a : Get Training and Test Data

In [0]:
trainX = mnist.train.images
trainY = mnist.train.labels

In [0]:
testX = mnist.test.images
testY = mnist.test.labels

How many Training and Test Examples?

In [0]:
trainY[0:1]

array([[0., 0., 0., 0., 0., 0., 0., 1., 0., 0.]])

In [0]:
#dic of values for defining LR value and the batch size
#Dictionary  {0.001: 200, 0.003: 250, 0.015: 150, 0.05: 300, 0.2: 275}
dict_lrsb = dict([(0.3, 200),(0.8,250),(0.015,150),(0.05,300),(0.2,275)])
print ('Dictionary ',dict_lrsb)
print ('Learning Rate : ',dict_lrsb.keys())
print ('Batch Size : ',dict_lrsb.values())


Dictionary  {0.3: 200, 0.8: 250, 0.015: 150, 0.05: 300, 0.2: 275}
Learning Rate :  dict_keys([0.3, 0.8, 0.015, 0.05, 0.2])
Batch Size :  dict_values([200, 250, 150, 300, 275])


In [0]:
from collections import defaultdict
 
my_default_dict = defaultdict(list)
 
# Lets add 10 values to "My Key"
for i in range(5):
 #print dict_lrsb[i] 
 learning_rate = (list(dict_lrsb)[i])
 print (learning_rate)
 print (dict_lrsb[learning_rate])
 #print (list(dict_lrsb.values()[i]))
 #my_default_dict["My Key"].append(i)
 
#print(my_default_dict["My Key"])

In [0]:
for key,value in dict_lrsb.items():
  print ( 'LR : ',key  ,': Batch Sz ', value)

Lets define some parameters

In [0]:
logs_path = "/content/"
#learning_rate = 0.2
n_features = trainX.shape[1]
n_classes = trainY.shape[1]
model_name = 'mnist.ckpt'

#How many examples to feed for training at one time
#batch_size = 200

#How many times all the data to be shown
training_epochs = 250

J = 522
K = 340
L = 230
M = 150
N = 100
O = 66
P = 44


In [0]:
n_classes

10

# Build the Graph

Input placeholders

In [0]:
for key,value in dict_lrsb.items():
  print ( 'LR : ',key  ,': Batch Sz ', value)

In [0]:
for a in range(5):

  learning_rate = (list(dict_lrsb)[a])
  #print (learning_rate)
  batch_size = (dict_lrsb[learning_rate])
  #print (batch_size)
  print ("Learing Rate, Batch Size : ", learning_rate ,batch_size )

  with tf.name_scope('input'):
    # None -> batch size can be any size, with n_features
    x = tf.placeholder(tf.float32, shape=[None, n_features], name="x-input") 
    # target n_classes output classes
    y_ = tf.placeholder(tf.float32, shape=[None, n_classes], name="y-input")
    
  with tf.name_scope('layer_1'):
    W1 = tf.Variable(tf.truncated_normal([n_features, J], stddev=0.1))
    b1 = tf.Variable(tf.zeros([J]))
    Y1 = tf.nn.sigmoid(tf.add(tf.matmul(x,W1),b1)) ## Y1 becomes the new x in the next iteration
  
  with tf.name_scope('layer_2'):
    W2 = tf.Variable(tf.truncated_normal([J, K], stddev=0.1))
    b2 = tf.Variable(tf.zeros([K]))
    Y2 = tf.nn.sigmoid(tf.add(tf.matmul(Y1,W2),b2))
  
  with tf.name_scope('layer_3'):
    W3 = tf.Variable(tf.truncated_normal([K, L], stddev=0.1))
    b3 = tf.Variable(tf.zeros([L]))
    Y3 = tf.nn.sigmoid(tf.add(tf.matmul(Y2,W3),b3))
    
  with tf.name_scope('layer_4'):
    W4 = tf.Variable(tf.truncated_normal([L, M], stddev=0.1))
    b4 = tf.Variable(tf.zeros([M]))
    Y4 = tf.nn.sigmoid(tf.add(tf.matmul(Y3,W4),b4))
  
  with tf.name_scope('layer_5'):
    W5 = tf.Variable(tf.truncated_normal([M, N], stddev=0.1))
    b5 = tf.Variable(tf.zeros([N]))
    Y5 = tf.nn.sigmoid(tf.add(tf.matmul(Y4,W5),b5))
    
  with tf.name_scope('layer_6'):
    W6 = tf.Variable(tf.truncated_normal([N, O], stddev=0.1))
    b6 = tf.Variable(tf.zeros([O]))
    Y6 = tf.nn.sigmoid(tf.add(tf.matmul(Y5,W6),b6))
  
  with tf.name_scope('layer_7'):
    W5 = tf.Variable(tf.truncated_normal([M, N], stddev=0.1))
    b5 = tf.Variable(tf.zeros([N]))
    Y5 = tf.nn.sigmoid(tf.add(tf.matmul(Y4,W5),b5))
    
  with tf.name_scope("Output"):
    W6 = tf.Variable(tf.truncated_normal([N,n_classes], stddev=0.1))
    b6 = tf.Variable(tf.zeros([n_classes]))
    y = tf.nn.softmax(tf.matmul(Y5,W6) + b6)
  
  with tf.name_scope('Loss'):
    cross_entropy = tf.reduce_mean(-tf.reduce_sum(y_ * tf.log(y), reduction_indices=[1]))
  
  with tf.name_scope('train'):        
    train_op = tf.train.GradientDescentOptimizer(learning_rate).minimize(cross_entropy)    ####LR
    
  with tf.name_scope('Accuracy'):
    prediction = tf.argmax(y,1,name="Predict")    
    correct_prediction = tf.equal(prediction, tf.argmax(y_,1))
    accuracy = tf.reduce_mean(tf.cast(correct_prediction, tf.float32),name="accuracy")  
    
 # create a summary for our cost and accuracy
  training_loss = tf.summary.scalar("training_loss", cross_entropy)
  training_accuracy = tf.summary.scalar("training_accuracy", accuracy)
  test_loss = tf.summary.scalar("test_loss", cross_entropy)
  test_accuracy = tf.summary.scalar("test_accuracy", accuracy)
  
  #Create a Saver to save the graph
  saver = tf.train.Saver()
  
  #Start Graph execution
  with tf.Session() as sess:
   # variables need to be initialized before we can use them
      sess.run(tf.global_variables_initializer())

      # create log writer object
      writer = tf.summary.FileWriter(logs_path, graph=tf.get_default_graph())

      # perform training cycles
      for epoch in range(training_epochs):
        
        # number of batches in one epoch
        batch_count = int(trainX.shape[0]/batch_size)
    
    
        for i in range(batch_count):
            batch_x  = trainX[i*batch_size:i*batch_size+batch_size]
            batch_y  = trainY[i*batch_size:i*batch_size+batch_size]

            # perform the operations we defined earlier on batch
            _,acc,loss = sess.run([train_op, training_accuracy,training_loss], feed_dict={x: batch_x, y_: batch_y})
            
            #log training accuracy and loss
            writer.add_summary(acc, epoch * batch_count + i)
            writer.add_summary(loss, epoch * batch_count + i)    
                       
      #Test loss and accuracy
        #pls note we are giving test data
        acc,loss = sess.run([test_accuracy,test_loss],feed_dict={x: testX, y_: testY})
        writer.add_summary(acc, epoch * batch_count + i)
        writer.add_summary(loss, epoch * batch_count + i)
        
        if epoch % 25 == 0: 
            print ("Epoch: ", epoch)
            print ("Test Accuracy: ", accuracy.eval(feed_dict={x: testX, y_: testY}))               
    
    
    #Save the model
      writer = tf.summary.FileWriter('./graphs', sess.graph)
      saver.save(sess, logs_path + '/' + model_name)

Learing Rate, Batch Size :  0.3 200
Epoch:  0
Test Accuracy:  0.0958
Epoch:  25
Test Accuracy:  0.9574
Epoch:  50
Test Accuracy:  0.9718
Epoch:  75
Test Accuracy:  0.9734
Epoch:  100
Test Accuracy:  0.9726
Epoch:  125
Test Accuracy:  0.975
Epoch:  150
Test Accuracy:  0.9756
Epoch:  175
Test Accuracy:  0.9755
Epoch:  200
Test Accuracy:  0.9759
Epoch:  225
Test Accuracy:  0.9756
Learing Rate, Batch Size :  0.8 250
Epoch:  0
Test Accuracy:  0.0958
Epoch:  25
Test Accuracy:  0.9719
Epoch:  50
Test Accuracy:  0.9755
Epoch:  75
Test Accuracy:  0.976
Epoch:  100
Test Accuracy:  0.9781
Epoch:  125
Test Accuracy:  0.9785
Epoch:  150
Test Accuracy:  0.9794
Epoch:  175
Test Accuracy:  0.9794
Epoch:  200
Test Accuracy:  0.9793
Epoch:  225
Test Accuracy:  0.9796
Learing Rate, Batch Size :  0.015 150
Epoch:  0
Test Accuracy:  0.1028
Epoch:  25
Test Accuracy:  0.1028
Epoch:  50
Test Accuracy:  0.3865
Epoch:  75
Test Accuracy:  0.6831
Epoch:  100
Test Accuracy:  0.851
Epoch:  125
Test Accuracy:  0.894